### PR TITLE
Move to Clay + Enamel

### PR DESCRIPTION
**Pull request by gregoiresage**
Replace pebble-autoconfig by Clay + Enamel :-p

### CODE REVIEW

**Comment by kevincon** [comment]
Finally got a chance to try this PR, and unfortunately the config page doesn't load for me. It just sits on a black screen with a spinning progress wheel when I try to load the config page.

I'm on iOS running a beta build of the next version of the Pebble iOS app, so maybe that has something to do with the problem. What version of the Pebble mobile app are you running? Are you on iPhone or Android? And it worked for you, right?

**Comment by gregoiresage** [comment]
Yes I have just tried on Android (3.10.0-976-0c219e8) and it is working...

**Comment by gregoiresage** [comment]
do you still have the problem on ios ?

**Comment by kevincon** [comment]
I can see the config page now on iOS, but it isn't showing the default colors for this watchface. This is what I see instead:

img_3513

**Comment by gregoiresage** [comment]
Yes, that's a Clay limitation. Colorpickers only accept Pebble colors.
Maybe @keegan-liloo can do something about that :-p

**Comment by keegan-lillo** [comment]
Is there a reason your default colors are not one of the Pebble colors?

**Comment by kevincon** [comment]
The hex values I'm using are more accurate representations of the Simpsons sky blue and red logo type colors. I know they currently just quantize to one of the 64 current Pebble colors, but someday a Pebble device could exist that supports even more colors. 

Since Clay lets you input arbitrary hex values for default color values in config.json, can't it just map the hex value to the closest supported Pebble color for the current platform?

**Comment by gregoiresage** [comment]
I have updated the custom-clay.js
'Custom' colors are now correctly converted to pebble ones :-D

**Comment by kevincon** [comment]
Nice job fixing the colors! Now from a fresh install (no instance of the Sprinkles watchface being in my locker on the Pebble Time app on my iPhone) I see the following on the config page:

img_3527

However I see this on the watch:

pebble_screenshot_2016-03-13_20-03-41

Notice that, despite the "Show date" option having a default value of `true`, it does not appear on the watchface. Any idea why that isn't working?

**Comment by gregoiresage** [comment]
Fixed! There was a typo in the config.json

**Comment by kevincon** [comment]
Awesome! I have just one more bug/quirk to report. If you tap one of the colors in the config menu to bring up the color picker, choose a color (observing that the color changes immediately on the watch), and then tap "Cancel" in the upper right hand corner (instead of tapping "Done"), then the watch continues to use the new color but if you then re-open the config menu it will still show the old color as the current choice. Any ideas on how to fix that? 

My thought is that it should either 1) revert to the old color on the watch if the "Cancel" button is tapped or 2) tapping the "Cancel" button should also update the saved value for the config option so they stay in sync.

**Comment by keegan-lillo** [comment]
Just for posterity, https://github.com/pebble/clay/pull/54 will do the color rounding for you :)

**Comment by gregoiresage** [comment]
@kevincon I don't know how to implement solution 1 (on android the webviewclosed callback is no more called on cancel...)
Solution 2 is possible

**Comment by gregoiresage** [comment]
If liveconfig is an issue, we can remove it from the project :-p

**Comment by kevincon** [comment]
Sweet! One more issue:
1. Install Sprinkles watchface built from this pull request.
2. Open config page and change some colors.
3. Reinstall watchface built from this pull request.
4. See that watchface on watch is using the default colors.
5. Open config page, see that the config page does not show the default colors but instead shows the changed colors from step (2).

Note that tapping "Done" in the config page after step (5) does update the watchface correctly to show the changed colors from step (2), but is there anything we can do about this?

**Comment by gregoiresage** [comment]
I think the watch persistent storage is cleared when an app is installed
with the sdk/cloudpebble or sideloaded. But the javascript storage is not
(cleared only when we uninstall the watchface).
This will not happen when the face is updated from the appstore.

When can probably send the old js storage in the js 'ready' callback but it
is a problem you will see only in development.

Tell me if I am wrong

**Comment by gregoiresage** [comment]
Relative to my previous comment : 
I tried on android and I don't reproduce your problem... Watch and config page are synchronized even after a new install (old settings are saved)

Does the problem occur only on ios ?

**Comment by kevincon** [comment]
Yeah it's still an issue on iOS. I guess this isn't the worst problem in the world, but it's disappointing that Clay/Enamel won't use the existing user settings from the previous version of the watchface, at least on iOS.

Here's a more likely scenario that users will run into and what happens for me on iOS:

1) Install Sprinkles from app store.
2) Open config page and set some custom colors.
3) Sideload-install Sprinkles from this PR.
3) Observe on watch that default colors are used instead of settings from (2).
4) Open config page and see that default colors are set instead of settings from (2).

If there's nothing we can do to fix it then I guess that's all we can do, but can you let me know if you can reproduce this behavior on Android? I'm just curious if at least the Android users won't suffer from this issue. :)

**Comment by gregoiresage** [comment]
Sprinkles from the appstore uses pebble-autoconfig but the version form this pull request uses enamel.
Theorically, the 2 frameworks can be different and they can store the data differently.
Actually, pebble-autoconfig saves data in the javascript with `localStorage.setItem('sprinkles')` but Clay does `localStorage.setItem('clay-settings')` (with its own 'encoding'), so the migration between autoconfig and clay is not straightforward.
On the C side, autoconfig stores each setting with a dedicated key, as Enamel does.

On Android : 
3) I observe the same settings on the watch as (2)
4) The config page displays the default color and not the settings from (2)

**Comment by kevincon** [comment]
Ah I understand, well I guess it's just a cost users will have to pay once when moving from the pebble-autoconfig version of a watchface to the enamel version of the same watchface, but I don't think it's too bad.

Thanks again for your work on this! :)

**Pull request merged**
