### PR TITLE
Add live configuration

### PR DESCRIPTION
**Pull request by gregoiresage**
With the last version of pebble-autoconfig, the settings are automatically send to the watch without pressing the save button.
It is easier to modify/test the settings and see directly the changes on the watch.

It works great on android, I don't have access to an ios device... Maybe you can try and give me your feedback

Thanks

### CODE REVIEW

**Comment by kevincon** [comment]
Hey, thanks so much for the pull request and sorry I didn't respond to it sooner.

I tested the live config and it seems to work, although it's a little weird for there to still be "SAVE" buttons if the changes are saved immediately, don't you think?

Also, I appreciate your changing of the default colors from hex values to Pebble named colors, but they're not exactly the same. For example, here's the screenshot of the default configuration of the current release in the App Store:

image

And here's what it looks like with your changes:

screen shot 2016-02-15 at 8 54 51 pm

It's important to me that the previous blue is maintained because it more closely matches the Simpsons sky blue:

image

Besides, I think it's better to keep the default colors encoded as hex values so that, if the SDK supports more than 64 colors in the future, then the app will already be setup to use the most accurate color. Does that make sense? If so, can you revert those changes in appinfo.json?

**Comment by gregoiresage** [comment]
Hey Kevin,

I have fixed the color and updated the version of pebble-autoconfig, the changes are immedialtely visible now (not after ~1 second).
I will update the tool to remove the 'Save' button and give the posiibility to configure the color as hex value

**Comment by kevincon** [comment]
Err, can you change it back to the hex values? See my previous comment:

> Besides, I think it's better to keep the default colors encoded as hex values so that, if the SDK supports more than 64 colors in the future, then the app will already be setup to use the most accurate color.

**Comment by gregoiresage** [comment]
Yes, I understand but I cannot revert to hex values immediately, the tool doens't support them anymore. But I will update it to suport both hex value and Pebble enum. Is that okay ?

NB: as you know, the Slate color picker doesn't support colors that are not Pebble's ones so your hex color will be rounded to a Pebble color

**Comment by kevincon** [comment]
Ah I understand, yes that sounds good. Thanks!

**Comment by gregoiresage** [comment]
Do you think it is better to use the sunny palette or the normal one for the slate color picker ?

**Comment by gregoiresage** [comment]
And if you enter a not-pebble color in the default value of your setting, what is the expected behaviour ?

**Comment by gregoiresage** [comment]
It should be okay now

**Comment by gregoiresage** [comment]
Clay is almost released... It will destroy pebble-autoconfig :-p

**Comment by kevincon** [comment]
Awesome! One thing that I'm not sure about, though, is that It appears that the watchface's default colors are shown non-muted (normal mode I think?) in the config page preview, but then if you select a muted color (sunny mode?) from the color picker then the muted version of it is displayed in the config page preview. Do you see what I'm talking about? Could we make it consistent, perhaps by just using the normal color picker?

I think if someone entered a non-Pebble color in hex as a default value, then ideally the closest Pebble color would be used.

I'm not sure what's going on with Clay, but it seems like it's been in development for a while, so I think there's still a need for pebble-autoconfig in the meantime. :)

**Comment by gregoiresage** [comment]
Using normal color picker now :-p

**Comment by kevincon** [comment]
Fantastic! Excellent work, and thanks so much for your contribution to the Pebble community. :)

**Pull request merged**
